#' @title Calculate Intensity Distribution
#' 
#' @description Calculate intensity distribution for a well
#' 
#' @param plateIndir The directory name of the plate as generated by the microscope (Unnecessary, only here for consistent signature)
#' @param platename The ID (and folder name) of the plate
#' @param row The row of the well
#' @param col The column of the well
#' @param configdir The configuration file, which defines the number of z-stacks, channels, and fields
#' 
#' @return A boolean value indicating if the save was successful
#' 
#' @author Jan Sauer
#' 
#' @examples print(calcIntensityDistribution)
#' @export
calcIntensityDistribution <- function(plateIndir, platename, row, col, configdir) {
  source(file.path(configdir, "watchdogConfig.R"))
  # Load hdf5projection
  
  proj_fn = projectionHdf5Filename(file.path(hdf5projection, platename), platename = platename, row = row, col = col)
  img = h5read(file = proj_fn, name = "images")
  nFields = dim(img)[4]
  nChannels = dim(img)[3]
  full_counts = array(data = 0, dim = c(65536, nChannels, nFields, 1), 
                      dimnames = list(as.character(0:65535), NULL, NULL, NULL))
  for(fld in seq_len(nFields)) {
    for(ch in seq_len(nChannels)) {
      counts = table(as.numeric(img[,,ch,fld]))
      full_counts[names(counts), ch, fld, 1] = counts
    }
  }
  
  # Create file
  dir.create(file.path(featuresdir, "intensity_distribution", platename), showWarnings = FALSE, recursive = TRUE)
  h5fn = intensityHdf5Filename(filedir = file.path(featuresdir, "intensity_distribution", platename), platename = platename, row = row, col = col)
  file_made = h5createFile(h5fn)
  if(!file_made) {H5close(); return(FALSE)}
  
  dataset_made = h5createDataset(file = h5fn, dataset = "features", dims = dim(full_counts), 
                                 H5type = "H5T_NATIVE_UINT32", level = hdf5_compression)
  if(!dataset_made) {H5close(); return(FALSE)}
  h5write(obj = full_counts, file = h5fn, name = "features")
  h5write(obj = paste0(platename, "_", row, "_", col), file = h5fn, name = "well_ids")
  H5close()
}