#' @title Rename TIFF files to the expected format
#' 
#' @description Rename all TIFF files of in a plate folder to the expected format
#' 
#' @param plateIndir The directory name of the plate as generated by the microscope
#' @param configdir The configuration file, which defines the number of z-stacks, channels, and fields
#' 
#' @return A boolean value indicating if the rename was successful
#' 
#' @author Jan Sauer
#' 
#' @examples print(renameTIFF)
#' @export
renameTIFF <- function(plateIndir, configdir) {
  source(file.path(configdir, "watchdogConfig.R"))
  
  full_path = file.path(indir, plateIndir)
  filenames = list.files(full_path)
  
  filenames_new = str_replace(
    string = filenames, pattern = "- ([0-9]{1})\\(", replacement = "- 0\\1(")
  filenames_new = str_replace(
    string = filenames_new, pattern = "z ([0-9]{1})\\)", 
    replacement = "z 0\\1)")
  
  full_paths_old = file.path(indir, plateIndir, filenames)
  full_paths_new = file.path(indir, plateIndir, filenames_new)
  
  # Keep only changed file names
  sel_indicies = !file.exists(full_paths_new)
  full_paths_old = full_paths_old[sel_indicies]
  full_paths_new = full_paths_new[sel_indicies]
  
  output = file.symlink(from = full_paths_old, full_paths_new)
  return(all(output))
}