#' @title DNN Segmentation
#' 
#' @description This calls the python script to perform the DNN segmentation
#' 
#' @param plateIndir The directory name of the plate as generated by the microscope
#' @param platename The ID (and folder name) of the plate
#' @param row The row of the well
#' @param col The column of the well
#' @param configdir The configuration file, which defines the number of z-stacks, channels, and fields
#' 
#' @return NULL
#' 
#' @author Jan Sauer
#' 
#' @examples print(segmentation)
#' @export
segmentation <- function(plateIndir, platename, row, col, configdir) {
  source(file.path(configdir, "watchdogConfig.R"))
  
  exec_script = file.path(pythondir, pythonexec)
  infile = projectionHdf5Filename(filedir = file.path(hdf5projection, platename), platename = platename, row = row, col = col)
  outfile = segmentationHdf5Filename(filedir = file.path(segmentationdir, platename), platename = platename, row = row, col = col)  
  output = system(sprintf("python %s %s %s %s %s", exec_script, platename, infile, outfile, pythondir))
}

