#' @title Turn a series of TIF images into an HDF5 file
#' 
#' @description This function stores all images associated with a well in an HDF5 file
#' 
#' @param plateIndir The directory name of the plate as generated by the microscope
#' @param platename The ID (and folder name) of the plate
#' @param row The row of the well
#' @param col The column of the well
#' @param configdir The configuration file, which defines the number of z-stacks, channels, and fields
#' 
#' @return A boolean value indicating if the save was successful
#' 
#' @author Jan Sauer
#' 
#' @examples print(tif2HDF5)
#' @export
tif2HDF5 <- function(plateIndir, platename, row, col, configdir) {
  source(file.path(configdir, "watchdogConfig.R"))
  
  filenames = imageFilenames(plateIndir, platename, row, col, configdir)
  
  # Check that all images are present
  identifiers = expand.grid(fields, channels, stacks, stringsAsFactors = FALSE)
  # all_filenames = apply(identifiers, 1, function(x) singleImageFilename(configdir, row, col, x[[1]], x[[2]], x[[3]]))
  # if(!setequal(all_filenames, filenames)) {
  #   warning(sprintf("Not all filenames present in (plate: %s, well: %s %s)", platename, row, col))
  #   return(FALSE)
  # }
  
  # Create hdf5 file (and folders if necessary)
  dir.create(file.path(hdf5dir, platename), showWarnings = FALSE, recursive = TRUE)
  h5FileName = hdf5Filename(filedir = file.path(hdf5dir, platename), platename = platename, row = row, col = col)
  file_made = h5createFile(h5FileName)
  if(!file_made) {H5close(); return(FALSE)}
  
  # Create datasets
  dataset_made = h5createDataset(file = h5FileName, dataset = "images", dims = c(2048, 2048, length(stacks), length(channels), length(fields)), 
                                 H5type = "H5T_NATIVE_UINT16", chunk = c(hdf5_chunksize, hdf5_chunksize, 1, 1, 1), level = hdf5_compression)
  if(!dataset_made) {H5close(); return(FALSE)}
  
  # Write metadata
  donor = substr(x = platename, 1, 4)
  site = substr(x = platename, 5, 7)
  plateid = substr(x = platename, 8, 11)
  layout = substr(x = platename, 12, 14)
  well = paste0(row, col)
  channels_string = paste0(channels, collapse = "_")
  infoimg = suppressWarnings(readTIFF(filenames[1], info = TRUE))
  resolution.x = attr(infoimg, "x.resolution")
  resolution.y = attr(infoimg, "y.resolution")
  resolution.unit = attr(infoimg, "resolution.unit")
  timestamp = attr(infoimg, "date.time")

  metadata = matrix(data = c("Donor", donor, "Site", site, "Plate", plateid, "Layout", layout, "Well", well, "Channels", channels_string,
                             "Resolution.X", resolution.x, "Resolution.Y", resolution.y, "Resolution.units", resolution.unit,
                             "Timestamp", timestamp, "PackageVersion", as.character(packageVersion("PROMISE"))), 
                    ncol = 2, byrow = TRUE)
  
  # metadata_made = h5createDataset(file = h5FileName, dataset = "metadata", dims = dim(metadata), storage.mode = "character", size = 50, level = hdf5_compression)
  # if(!metadata_made) {H5close(); return(FALSE)}
  #
  h5write(obj = metadata, file = h5FileName, name = "metadata", level = hdf5_compression)
  
  # Write data
  for(i in seq_len(nrow(identifiers))) {
    id = identifiers[i,]
    f_index = which(id[,1] == fields)
    c_index = which(id[,2] == channels)
    z_index = which(id[,3] == stacks)
    imgName = singleImageFilename(configdir, row, col, id[,1], id[,2], id[,3])
    img = suppressWarnings(readImage(file.path(indir, plateIndir, imgName), as.is = TRUE))
    h5write(obj = img@.Data, file = h5FileName, name = "images", index=list(NULL, NULL, z_index, c_index, f_index))
  }
  H5close()
  return(TRUE)
}

# Image files
# Donor
# site
# plate
# layout
# well
# resolution
# timestamp
# channel names
# version

## in image file
# channel names
# ome-tiff header

#library(tiff)
#Img = readTIFF("A - 03(fld 5 wv Cy3 - Cy3 z 04).tif",info = TRUE)
#attributes(Img)
