#' @title TIF Diagnostics
#' 
#' @description This extracts all files that are not well images and places them in a diagnostics directory
#' 
#' @param plateIndir The directory name of the plate as generated by the microscope
#' @param platename The ID (and folder name) of the plate
#' @param configdir The configuration file, which defines the number of z-stacks, channels, and fields
#' 
#' @return NULL
#' 
#' @author Jan Sauer
#' 
#' @examples print(moveTifDiagnostics)
#' @export
moveTifDiagnostics <- function(plateIndir, platename, configdir) {
  source(file.path(configdir, "watchdogConfig.R"))
  
  # Make directory
  outdir = file.path(tifdiagnosticsdir, platename)
  if(!file.exists(outdir)) {
    dir.create(outdir, showWarnings = FALSE, recursive = TRUE)
  }
  
  # Get non-well files
  all_files = list.files(file.path(indir, plateIndir))
  nonwell_bool = grepl("^[A-Z] - .*", all_files)
  nonwell_files = all_files[!nonwell_bool]
  
  # Manually remove any directories
  nonwell_files = nonwell_files[!file.exists(file.path(indir, plateIndir, paste0(nonwell_files, "/")))]
  
  # Move files
  success = file.rename(file.path(indir, plateIndir, nonwell_files), file.path(outdir, nonwell_files))
  
  return(all(success))
}