#' @title Validates HDF5 files of raw image data
#' 
#' @description This function checks that the HDF5 file created for a well matches the raw image files
#' 
#' @param plateIndir The directory name of the plate as generated by the microscope
#' @param platename The ID (and folder name) of the plate
#' @param row The row of the well
#' @param col The column of the well
#' @param configdir The configuration file, which defines the number of z-stacks, channels, and fields
#' 
#' @return A boolean value indicating if the two files match
#' 
#' @author Jan Sauer
#' 
#' @examples print(validateHDF5)
#' @export
validateHDF5 <- function(plateIndir, platename, row, col, configdir) {
  source(file.path(configdir, "watchdogConfig.R"))
  
  identifiers = expand.grid(fields, channels, stacks, stringsAsFactors = FALSE)
  h5Filename = hdf5Filename(filedir = file.path(hdf5dir, platename), platename = platename, row = row, col = col)
  all_images_identical = TRUE
  
  # Loop through all images and compare to the corresponding hdf5 slice
  for(img_id in seq_len(nrow(identifiers))) {
    cat(img_id, "\n")
    field = identifiers[img_id, 1]
    channel = identifiers[img_id, 2]
    stack = identifiers[img_id, 3]
    img_name = singleImageFilename(configdir, row, col, field, channel, stack)
    img = suppressWarnings(readImage(file.path(indir, plateIndir, img_name), as.is = TRUE))
    
    field_id = match(field, fields)
    channel_id = match(channel, channels)
    stack_id = match(stack, stacks)
    h5slice = h5read(file = h5Filename, name = "images", index=list(NULL,NULL,stack_id,channel_id,field_id))[,,1,1,1]
    
    if(!identical(h5slice,img@.Data)) {
      all_images_identical = FALSE
      H5close()
      break
    }
  }
  
  H5close()
  
  dir.create(file.path(hdf5validationdir, platename), showWarnings = FALSE, recursive = TRUE)
  # writeLines(as.character(all_images_identical), file.path(hdf5validationdir, platename, sprintf("%s_%s_%s_isvalid.txt",platename, row, col)))
  writeLines(as.character(all_images_identical), validationHdf5Filename(file.path(hdf5validationdir, platename), platename, row, col))

  return(all_images_identical)
}
