
#' @import
#'  rhdf5
#'  ZProjection
#'  tiff
#'  hwriter
#'  stats
#'  utils
#'  EBImage
#'  stringr
invisible(NULL)

#' @title Full Workflow
#' 
#' @description This is the full PROMISE workflow
#' 
#' @param plateIndir The directory name of the plate as generated by the microscope
#' @param platename The ID (and folder name) of the plate
#' @param row The row of the well
#' @param col The column of the well
#' @param configdir The configuration file, which defines the number of z-stacks, channels, and fields
#' 
#' @return NULL
#' 
#' @author Jan Sauer
#' 
#' @examples print(PROMISEworkflow)
#' @export
PROMISEworkflow <- function(plateIndir, platename, row, col, configdir) {
    tif2HDF5(plateIndir, platename, row, col, configdir)
    validateHDF5(plateIndir, platename, row, col, configdir)
    moveTifDiagnostics(plateIndir, platename, configdir)
    projection(plateIndir, platename, row, col, configdir)
    thumbnailImages(plateIndir, platename, row, col, configdir)
    calcIntensityDistribution(plateIndir, platename, row, col, configdir)
    segmentation(plateIndir, platename, row, col, configdir)
    thumbnailSegmentation(plateIndir, platename, row, col, configdir)
    extractOrganoidFeatures(plateIndir, platename, row, col, configdir)
    invisible(NULL)
}

#' @title Conversion Workflow
#' 
#' @description This is the PROMISE workflow to convert TIF images into HDF5 format and test validity
#' 
#' @param plateIndir The directory name of the plate as generated by the microscope
#' @param platename The ID (and folder name) of the plate
#' @param row The row of the well
#' @param col The column of the well
#' @param configdir The configuration file, which defines the number of z-stacks, channels, and fields
#' 
#' @return NULL
#' 
#' @author Jan Sauer
#' 
#' @examples print(PROMISEconversion)
#' @export
PROMISEconversion <- function(plateIndir, platename, row, col, configdir) {
  tif2HDF5(plateIndir, platename, row, col, configdir)
  validateHDF5(plateIndir, platename, row, col, configdir)
  moveTifDiagnostics(plateIndir, platename, configdir)
  invisible(NULL)
}

#' @title Conversion + Projection Workflow
#' 
#' @description This is the Conversion and Projection step of the workflow
#' 
#' @param plateIndir The directory name of the plate as generated by the microscope
#' @param platename The ID (and folder name) of the plate
#' @param row The row of the well
#' @param col The column of the well
#' @param configdir The configuration file, which defines the number of z-stacks, channels, and fields
#' 
#' @return NULL
#' 
#' @author Jan Sauer
#' 
#' @examples print(PROMISEworkflow)
#' @export
PROMISEuntilprojection <- function(plateIndir, platename, row, col, configdir) {
  tif2HDF5(plateIndir, platename, row, col, configdir)
  validateHDF5(plateIndir, platename, row, col, configdir)
  moveTifDiagnostics(plateIndir, platename, configdir)
  projection(plateIndir, platename, row, col, configdir)
  thumbnailImages(plateIndir, platename, row, col, configdir)
  calcIntensityDistribution(plateIndir, platename, row, col, configdir)
  invisible(NULL)
}

#' @title Projection Workflow
#' 
#' @description This is the PROMISE workflow to project HDF5 stacks
#' 
#' @param plateIndir The directory name of the plate as generated by the microscope
#' @param platename The ID (and folder name) of the plate
#' @param row The row of the well
#' @param col The column of the well
#' @param configdir The configuration file, which defines the number of z-stacks, channels, and fields
#' 
#' @return NULL
#' 
#' @author Jan Sauer
#' 
#' @examples print(PROMISEprojection)
#' @export
PROMISEprojection <- function(plateIndir, platename, row, col, configdir) {
  projection(plateIndir, platename, row, col, configdir)
  thumbnailImages(plateIndir, platename, row, col, configdir)
  calcIntensityDistribution(plateIndir, platename, row, col, configdir)
  segmentation(plateIndir, platename, row, col, configdir)
  thumbnailSegmentation(plateIndir, platename, row, col, configdir)
  extractOrganoidFeatures(plateIndir, platename, row, col, configdir)
  invisible(NULL)
}

#' @title Projection Only Workflow
#' 
#' @description This is the PROMISE workflow to project HDF5 stacks
#' 
#' @param plateIndir The directory name of the plate as generated by the microscope
#' @param platename The ID (and folder name) of the plate
#' @param row The row of the well
#' @param col The column of the well
#' @param configdir The configuration file, which defines the number of z-stacks, channels, and fields
#' 
#' @return NULL
#' 
#' @author Jan Sauer
#' 
#' @examples print(PROMISEprojectionOnly)
#' @export
PROMISEprojectionOnly <- function(plateIndir, platename, row, col, configdir) {
  projection(plateIndir, platename, row, col, configdir)
  thumbnailImages(plateIndir, platename, row, col, configdir)
  calcIntensityDistribution(plateIndir, platename, row, col, configdir)
  invisible(NULL)
}

#' @title Segmentation Workflow
#' 
#' @description This is the PROMISE workflow to segment HDF5 projections
#' 
#' @param plateIndir The directory name of the plate as generated by the microscope
#' @param platename The ID (and folder name) of the plate
#' @param row The row of the well
#' @param col The column of the well
#' @param configdir The configuration file, which defines the number of z-stacks, channels, and fields
#' 
#' @return NULL
#' 
#' @author Jan Sauer
#' 
#' @examples print(PROMISEsegmentation)
#' @export
PROMISEsegmentation <- function(plateIndir, platename, row, col, configdir) {
  segmentation(plateIndir, platename, row, col, configdir)
  thumbnailSegmentation(plateIndir, platename, row, col, configdir)
  extractOrganoidFeatures(plateIndir, platename, row, col, configdir)
  invisible(NULL)
}

#' @title Segmentation Only Workflow
#' 
#' @description This is the PROMISE workflow to segment HDF5 projections
#' 
#' @param plateIndir The directory name of the plate as generated by the microscope
#' @param platename The ID (and folder name) of the plate
#' @param row The row of the well
#' @param col The column of the well
#' @param configdir The configuration file, which defines the number of z-stacks, channels, and fields
#' 
#' @return NULL
#' 
#' @author Jan Sauer
#' 
#' @examples print(PROMISEsegmentation)
#' @export
PROMISEsegmentationOnly <- function(plateIndir, platename, row, col, configdir) {
  segmentation(plateIndir, platename, row, col, configdir)
  thumbnailSegmentation(plateIndir, platename, row, col, configdir)
  invisible(NULL)
}

#' @title Feature Extraction Workflow
#' 
#' @description This is the PROMISE workflow to extract features
#' 
#' @param plateIndir The directory name of the plate as generated by the microscope
#' @param platename The ID (and folder name) of the plate
#' @param row The row of the well
#' @param col The column of the well
#' @param configdir The configuration file, which defines the number of z-stacks, channels, and fields
#' 
#' @return NULL
#' 
#' @author Jan Sauer
#' 
#' @examples print(PROMISEfeatures)
#' @export
PROMISEfeatures <- function(plateIndir, platename, row, col, configdir) {
  extractOrganoidFeatures(plateIndir, platename, row, col, configdir)
  invisible(NULL)
}
